### PR TITLE
iPhone X Support

### PR DESCRIPTION
**Pull request by losh11**
~~Not yet complete. Most of the UI should look fine now.~~

**TODOs:**

- [x] FaceID references
- [x] cleanup
- [x] PIN Required menu constraints

Not the best way to do things, but acceptable I think. I'll try to finish everything tomorrow :)

### CODE REVIEW

**Comment by losh11** [comment]
Looks like I forgot to commits some changes and accidentally stashed them - never mind.

**Comment by losh11** [comment]
Complete. Now we need locale, which is done through PhraseApp.

**Comment by nachoaIvarez** [comment]
What's the issue, problem, inconvenient or obstacle with this PR @acorscadden, @voisine, @samuraisam, @jmacwhyte, @dts and @Gutyn? Is there anything I can do to help get it merged? Is it related with implementation? Would it help to mimic [iPhoneX changes in LoafWallef](https://github.com/litecoin-foundation/loafwallet-ios/commits/master)?

The app looks ugly in iPhone X. Let's fix this.

**Comment by jmacwhyte** [comment]
@nachoaIvarez Fixes for iPhoneX have been included in the upcoming iOS update. Please keep an eye out for that and let me know if you think improvements still need to be made. We have improved our dev process and structure a lot lately, so future community contributions like this will be handled better. :)

**Comment by nachoaIvarez** [comment]
Thank you for your answer. I'm glad the update's incoming! Thank you for your fantastic work, best bitcoin wallet by far! Is there somewhere I can read about the development process @jmacwhyte? Particularly curious about the lightning protocol? Any plans to integrate it on the Wallet?

**Pull request merged**
