### PR TITLE
Update README Install Steps

### PR DESCRIPTION
**Pull request by joelklabo**
- Add submodule init step
- Install SwiftLint

### CODE REVIEW

**Comment by Alfonso-ops** [comment]
> - Add submodule init step
> 
> - Install SwiftLint

> - how do I get there?

**Comment by joelklabo** [comment]
> > * Add submodule init step
> > * Install SwiftLint
> 
> > * how do I get there?

Hi @Alfonso-ops  is that a suggested update?

**Review by alisscco — APPROVED** [review]

**Comment by mkinney** [comment]
I had to run this:

```git submodule update --init --recursive --remote```

then

```git submodule update --recursive```

**Review by Dpalazue — APPROVED** [review]

**Review by Kenny7213 — APPROVED** [review]

**Review by Kenny7213 — APPROVED** [review]
I’m confused. I wish someone would help explain things to me

**Comment by mkinney** [comment]
> I’m confused. I wish someone would help explain things to me

Confused about what exactly?

**Pull request closed without merging**
